export default {
  '-2': 'On Fire!',
  '-1': 'Descripcion',
  1: 'Usuario y/o contraseña incorrectos',
  2: 'Uno o mas parametros son inválidos',
  3: 'Acceso denegado',
  4: 'Tiempo de actividad agotado',
  5: 'Usted no tiene permiso para efectuar esta actividad',
  6: 'Ha ocurrido un error mientras se intentaba validar su acceso',
  7: 'No ha proporcionado un token de acceso',
  8: 'Ha ocurrido un error inesperado',
  9: 'La empresa indicada no existe o usted no pertenece a ella',
  10: 'Acción realizada satisfactoriamente',
  99: 'Imposible obtener la información o imposible almacenar la información',
  100: 'Hay mas de una empresa con este rut',
  101: 'Ya existe una empresa con el identificador único tributario indicado',
  102: 'Uno o mas campos obligatorios no han sido proporcionados o son inválidos',
  103: 'El certificado digital es inválido o la contraseña es incorrecta',
  104: 'Error subiendo el archivo',
  105: 'No se pudo obtener folio',
  106: 'Folio no existe',
  107: 'No cuenta con el nivel suficiente para modificar parámetro',
  108: 'Error crítico',
  109: 'Existe un problema con la configuración del certificado digital',
  110: 'El parámetro no existe',
  111: 'El parámetro es de carácter interno.',
  112: 'El id de referencia no corresponde a ninguna empresa, grupo o usuario',
  113: 'No pertenece a la empresa que intenta asignar a otro usuario',
  114: 'Ya existe un usuario registrado con ese rut',
  115: 'Ya existe un usuario registrado con ese correo',
  116: 'No existe caf correspondiente al folio determinado',
  117: 'Imposible integrar documento',
  118: 'Ha ocurrido un error interno',
  119: 'Imposible firmar documento',
  10119: 'Imposible firmar documento',
  120: 'Imposible generar folio para el documento',
  121: 'No se puede encontrar el archivo especificado',
  122: 'La bitácora no contiene información',
  123: 'El registro que busca no se encuentra disponible o no fue encontrado',
  124: 'El archivo cambió mientras se estaba editando, imposible guardar cambios',
  125: 'Ha ocurrido un error mientras se intentaba guardar el archivo',
  126: 'No fue posible ubicar etiqueta en el xml',
  127: 'Documento al cual hace referencia no existe o no pertenece a la empresa consultada',
  128: 'Se esta intentando acceder a una configuración inexistente',
  129: 'El código único especificado ya existe, imposible integrar documento',
  130: 'Esta función ha sido deshabilitada para este ambiente',
  131: 'No se encontraron registros con los parámetros ingresados',
  133: 'No pertenece a ninguna empresa, debe pertenecer al menos a una',
  134: 'No puede eliminar la casa matriz',
  135: 'La entidad administradora de impuestos gubernamental no ha respondido a la solicitud',
  136: 'Imposible procesar la respuesta de la entidad administradora de impuestos gubernamental',
  137: 'El folio ingresado esta en uso',
  138: 'Ya existe un receptor registrado con ese rut',
  139: 'Ya existe un receptor registrado con ese correo',
  140: 'Uno o más de los correos electrónicos especificados son inválidos',
  141: 'La ruta al archivo o carpeta especificada es inválida',
  142: 'No se puede agregar el elemento debido a que ya existe en nuestros registros',
  143: 'El archivo que intenta cargar no es un archivo válido',
  144: 'El endpoint no ha respondido o ha respondido con error',
  145: 'El menu no puede ser eliminado ya que posee hijos, debe eliminar éstos primero',
  146: 'El elemento al que hace referencia, no existe.',
  147: 'El documento que intenta cargar no le pertenece.',
  148: 'El documento que intenta cargar ya existe en nuestros registros.',
  149: 'El Servicio de Impuestos Internos no ha podido procesar esta solicitud. Intente nuevamente.',
  150: 'El Servicio de Impuestos Internos ha rechazado la solicitud',
  151: 'El RUT especificado no esta registrado o no pertenece a ninguna empresa',
  152: 'La contraseña ingresada no es correcta, verifique e intente nuevamente',
  153: 'Rango de fechas no válido',
  154: 'Usuario no autorizado',
  155: 'Debe volver a loguearse nuevamente por clave única',
  156: 'Imposible parsear dato',
  157: 'Imposible obtener folios para el tipo de documento solicitado, valide por favor disponibilidad y vigencia ',
  158: 'No se puede cargar un rango de folios que ya existe.',
  159: 'No existen CAFs para esta empresa',
  160: 'El rut enviado en el XML no corresponde a la empresa emisora.',
  161: 'NO se encontro el archivo necesario para realzar la cesión',
  162: 'Documento ya se encuentra en proceso de cesión',
  163: 'TIPO DE DOCUMENTO NO ESTA PERMITIDO',
  164: '(SII) TOKEN ENVIADO NO ES VALIDO',
  165: 'Documento no se encuentra pendiente de envio',
  166: 'El rango de folios no es válido.',
  167: 'El ID de CAF no existe o no corresponde a ninguna empresa.',
  168: 'El CAF cargado está vencido, por favor validar fecha de autorización.',
  169: 'Imposible integrar documento recibido',
  170: 'El rut enviado en el XML no corresponde a una empresa receptora existente en nuestras bases.',
  171: 'El centro costo seleccionado ya se encuentra asociado a otro grupo.',
  172: 'El catálogo indicado no existe.',
  174: 'La empresa seleccionada no tiene catálogos.',
  173: 'El producto indicado no existe.',
  175: 'La empresa seleccionada no tiene productos.',
  176: 'La empresa seleccionada se encuentra suspendida y no puede ejecutar esta acción.',
  178: 'No se puede cambiar el estado si no esta en el paso actual',
  179: 'No se puede cambiar el estado si no es el responsable actual',
  180: 'No se puede cambiar el estado si no es parte del grupo de responsables del paso actual',
  181: 'El periodo de subrogancia ya a terminado, por lo cual no puedes realizar la acción',
  182: 'No podemos devolver la ejecución a un paso anterior o el paso no cuenta con la opcion para ser reenviado.',
  183: 'No se pudo publicar el archivo.',
  10176: 'El servicio externo no responde correctamente'
};
